import { Roboto } from "next/font/google";
import "../style/index.scss";
import Footer from "@/components/root-layout/Footer";
import Header from "@/components/root-layout/header/Header";

// Roboto fontunu ağırlıkları ile dahil ediyoruz
const roboto = Roboto({
  weight: ["400", "500", "700"],  // Kullanmak istediğiniz ağırlıkları belirtiyoruz
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased`} // Roboto fontunu burada uyguluyoruz
      >
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
